### ISSUE TITLE
apa yang dilakukan oleh perintah! ban?

### ISSUE THREAD

**Issue by NaldoMota1** [rzkytmgr/whatsapp-bot#1]
apa yang dilakukan oleh perintah! ban?

**Comment by rzkytmgr** [comment]
Hai @NaldoMota1 ,

perintah tersebut hanya dapat digunakan oleh **Owner Bot**
jika kamu menggunakan perintah tersebut terhadap seorang pengguna, maka bot akan mengabaikan pesan dari pengguna yang kamu tuju tadi. Jadi, pengguna tersebut tidak akan dapat menggunakan bot kembali, sebelum kamu melakukan _unbanned_ terhadap pengguna tersebut.
