### ISSUE TITLE
Session data most likely expired due to manual host account logout. Please re-authenticate this session.

### ISSUE THREAD

**Issue by sssain** [rzkytmgr/whatsapp-bot#10]
pas npm start ngga keluar qr code, tpi disuruh re-authenticate, btw ini start pertama kali.
![remmina_152 228 208 151_152 228 208 151_2021916-8508,064531](https://user-images.githubusercontent.com/64075541/133581947-9ed701f6-6825-4956-a609-643413e8b97f.png)

**Comment by rzkytmgr** [comment]
@nflzd segera di-update mas

**Comment by rzkytmgr** [comment]
hi, @nflzd . fixed!

silahkan kembali `git pull` lalu hapus `SAD_CLIENT.data.json`. setelah itu gunakan perintah `npm i` dan terakhir gunakan perintah `npm start`
Terima kasih,
