### ISSUE TITLE
eror bang, ga keluar qrcode nya

### ISSUE THREAD

**Issue by MSI0072** [rzkytmgr/WhatsApp-Bot#2]

**Comment by MSI0072** [comment]
![image](https://user-images.githubusercontent.com/63404067/96511758-b287dd00-1289-11eb-98d2-0704b4565b77.png)

**Comment by rzkytmgr** [comment]
Sudah saya perbaiki di PRs #3 , kamu bisa `git clone` ulang ya.
Closed
