### ISSUE TITLE
Whatsapp Automate @1.0.0

### ISSUE THREAD

**Issue by arieskurniawan** [rzkytmgr/whatsapp-bot#8]
Bang ini kok ga work ya? perasaan aku make automateku yg lama bisa bisa aja bang, tapi waktu di cmd node aku npm start selalu directori Whatsapp Automate @1.0.0 ga ada directori filenya

**Comment by rzkytmgr** [comment]
Sebelum di pakai pastikan dulu kamu udah install semua dependencies-nya `npm install` atau `npm i`

**Comment by arieskurniawan** [comment]
udah kak, cmn ga work selalu directory not file

**Comment by rzkytmgr** [comment]
bisa di screenshot atau bisa di copykan text errornya ?

**Comment by arieskurniawan** [comment]
![1](https://user-images.githubusercontent.com/49036222/120213997-b9e07300-c1e8-11eb-8a89-9a688a4d1e69.png)

**Comment by rzkytmgr** [comment]
Iya, itu errornya karena di node_modules nya belum kamu install depedenciesnya. pastikan dulu kamu install, coba clone ulang lalu kamu install ulang

**Comment by arieskurniawan** [comment]
![Uploading 1.png…]()

**Comment by arieskurniawan** [comment]
![1](https://user-images.githubusercontent.com/49036222/120343389-86b3e780-c2ad-11eb-8762-4cf3d96fa704.png)

**Comment by rzkytmgr** [comment]
Coba kamu clone ulang, habis itu kamu jalankan perintah `npm install` lagi.
kalau masih error open lagi issue ini. terus kasih penjelasan error-nya ya. makasih.
