### ISSUE TITLE
Some bugs on some features

### ISSUE THREAD

**Issue by yuhami** [rzkytmgr/whatsapp-bot#9]
saya menemukan beberapa bug di beberapa fitur, ada juga fitur yang tidak bekerja
ini daftar fiturnya

- [x] bot tidak dapat distart, tidak ada scan QR
- [ ] **!start** ketika di _**disable**_ tidak dapat di _**enable**_ kan kembali
- [x] **!music** error tidak ditemuka

**Comment by rzkytmgr** [comment]
Fixed, Untuk **!start** (fitur premium) sesegera mungkin saya perbaiki, saya akan umumkan di instagram saya **@rzkytmgr**
Silahkan re-open ya kalau ada problem lagi, Terima kasih.
